<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="signatureBaseModel" nsURI="http://org.bigraphs.model" nsPrefix="signatureBaseModel">
  <eClassifiers xsi:type="ecore:EClass" name="BDynamicSignature" eSuperTypes="#//BKindSignature"/>
  <eClassifiers xsi:type="ecore:EClass" name="BControl" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" ordered="false"
        lowerBound="1" eType="#//BControlStatus" defaultValueLiteral="ACTIVE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bSig" lowerBound="1" eType="#//BSorting"
        eOpposite="#//BSorting/bControls"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BControlStatus">
    <eLiterals name="ACTIVE"/>
    <eLiterals name="ATOMIC" value="1"/>
    <eLiterals name="PASSIVE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BKindPlaceSorting" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bPlaceSorting" lowerBound="1"
        eType="#//BKindSignature" eOpposite="#//BKindSignature/bKindPlaceSorts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bContainedBy" upperBound="-1"
        eType="#//BKindPlaceSorting" eOpposite="#//BKindPlaceSorting/bCanContain"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bCanContain" upperBound="-1"
        eType="#//BKindPlaceSorting" eOpposite="#//BKindPlaceSorting/bContainedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BKindSortNonAtomic" abstract="true"
      eSuperTypes="#//BKindPlaceSorting"/>
  <eClassifiers xsi:type="ecore:EClass" name="BKindSignature" eSuperTypes="#//BSorting">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bKindPlaceSorts" lowerBound="1"
        upperBound="-1" eType="#//BKindPlaceSorting" containment="true" eOpposite="#//BKindPlaceSorting/bPlaceSorting"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BKindSortAtomic" abstract="true" eSuperTypes="#//BKindPlaceSorting"/>
  <eClassifiers xsi:type="ecore:EClass" name="BSorting" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bControls" upperBound="-1"
        eType="#//BControl" containment="true" eOpposite="#//BControl/bSig"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BBasicSignature" eSuperTypes="#//BKindSignature"/>
</ecore:EPackage>
